# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: instant_messaging_service.proto for package 'messaging'

require 'grpc'
require 'instant_messaging_service_pb'

module Messaging
  module InstantMessageService
    # InstantMessageService can give us access to real time messages!
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'messaging.InstantMessageService'

      # Send sends a message to a user.  We don't use streaming here
      # because grpc-web doesn't handle client-side streaming.
      rpc :Send, AuthedIM, Message
      # Connect connects to an IM session with a user.
      rpc :Connect, ConnectAuth, stream(Message)
    end

    Stub = Service.rpc_stub_class
  end
end
