# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instant_messaging_service.proto

require 'google/protobuf'

require 'user_pb'
require 'message_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "messaging.ConnectAuth" do
    optional :auth, :message, 1, "messaging.Auth"
    optional :from, :message, 2, "messaging.Profile"
    optional :to, :message, 3, "messaging.Profile"
  end
  add_message "messaging.AuthedIM" do
    optional :auth, :message, 1, "messaging.Auth"
    optional :message, :message, 2, "messaging.Message"
  end
end

module Messaging
  ConnectAuth = Google::Protobuf::DescriptorPool.generated_pool.lookup("messaging.ConnectAuth").msgclass
  AuthedIM = Google::Protobuf::DescriptorPool.generated_pool.lookup("messaging.AuthedIM").msgclass
end
