# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

require 'google/protobuf'

require 'user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "messaging.Message" do
    optional :id, :string, 1
    optional :from, :message, 2, "messaging.Profile"
    optional :to, :message, 3, "messaging.Profile"
    optional :title, :string, 4
    optional :body, :string, 5
  end
  add_message "messaging.Thread" do
    optional :id, :string, 1
    repeated :messages, :message, 2, "messaging.Message"
  end
end

module Messaging
  Message = Google::Protobuf::DescriptorPool.generated_pool.lookup("messaging.Message").msgclass
  Thread = Google::Protobuf::DescriptorPool.generated_pool.lookup("messaging.Thread").msgclass
end
