# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_service.proto

require 'google/protobuf'

require 'user_pb'
require 'message_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "messaging.AuthedMessage" do
    optional :auth, :message, 1, "messaging.Auth"
    optional :message, :message, 2, "messaging.Message"
  end
  add_message "messaging.ThreadReply" do
    optional :auth, :message, 1, "messaging.Auth"
    optional :thread, :message, 2, "messaging.Thread"
    optional :message, :message, 3, "messaging.Message"
  end
end

module Messaging
  AuthedMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("messaging.AuthedMessage").msgclass
  ThreadReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("messaging.ThreadReply").msgclass
end
