# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto

require 'google/protobuf'

require 'user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "messaging.AuthedProfile" do
    optional :auth, :message, 1, "messaging.Auth"
    optional :profile, :message, 2, "messaging.Profile"
  end
end

module Messaging
  AuthedProfile = Google::Protobuf::DescriptorPool.generated_pool.lookup("messaging.AuthedProfile").msgclass
end
