# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user_service.proto for package 'messaging'

require 'grpc'
require 'user_service_pb'

module Messaging
  module UserService
    # UserService is our user microservice.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'messaging.UserService'

      # CreateUser creates a user.
      rpc :CreateUser, Ident, Profile
      # SetProfile updates a user's profile.
      rpc :SetProfile, AuthedProfile, Profile
    end

    Stub = Service.rpc_stub_class
  end
end
