# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import message_pb2 as message__pb2
import message_service_pb2 as message__service__pb2


class MessageServiceStub(object):
  """MessageService is our message microservice.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Send = channel.unary_unary(
        '/messaging.MessageService/Send',
        request_serializer=message__service__pb2.AuthedMessage.SerializeToString,
        response_deserializer=message__pb2.Thread.FromString,
        )
    self.Reply = channel.unary_unary(
        '/messaging.MessageService/Reply',
        request_serializer=message__service__pb2.ThreadReply.SerializeToString,
        response_deserializer=message__pb2.Thread.FromString,
        )
    self.Delete = channel.unary_unary(
        '/messaging.MessageService/Delete',
        request_serializer=message__service__pb2.AuthedMessage.SerializeToString,
        response_deserializer=message__pb2.Thread.FromString,
        )


class MessageServiceServicer(object):
  """MessageService is our message microservice.
  """

  def Send(self, request, context):
    """Send sends a new message to a user.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Reply(self, request, context):
    """Reply replies to a thread.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    """Delete deletes a message.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Send': grpc.unary_unary_rpc_method_handler(
          servicer.Send,
          request_deserializer=message__service__pb2.AuthedMessage.FromString,
          response_serializer=message__pb2.Thread.SerializeToString,
      ),
      'Reply': grpc.unary_unary_rpc_method_handler(
          servicer.Reply,
          request_deserializer=message__service__pb2.ThreadReply.FromString,
          response_serializer=message__pb2.Thread.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=message__service__pb2.AuthedMessage.FromString,
          response_serializer=message__pb2.Thread.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'messaging.MessageService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
