# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_pb2 as user__pb2
import message_pb2 as message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_service.proto',
  package='messaging',
  syntax='proto3',
  serialized_pb=_b('\n\x15message_service.proto\x12\tmessaging\x1a\nuser.proto\x1a\rmessage.proto\"T\n\rAuthedMessage\x12\x1e\n\x04\x61uth\x18\x01 \x01(\x0b\x32\x10.messaging.Ident\x12#\n\x07message\x18\x02 \x01(\x0b\x32\x12.messaging.Message\"u\n\x0bThreadReply\x12\x1e\n\x04\x61uth\x18\x01 \x01(\x0b\x32\x10.messaging.Ident\x12!\n\x06thread\x18\x02 \x01(\x0b\x32\x11.messaging.Thread\x12#\n\x07message\x18\x03 \x01(\x0b\x32\x12.messaging.Message2\xb6\x01\n\x0eMessageService\x12\x35\n\x04Send\x12\x18.messaging.AuthedMessage\x1a\x11.messaging.Thread\"\x00\x12\x34\n\x05Reply\x12\x16.messaging.ThreadReply\x1a\x11.messaging.Thread\"\x00\x12\x37\n\x06\x44\x65lete\x12\x18.messaging.AuthedMessage\x1a\x11.messaging.Thread\"\x00\x62\x06proto3')
  ,
  dependencies=[user__pb2.DESCRIPTOR,message__pb2.DESCRIPTOR,])




_AUTHEDMESSAGE = _descriptor.Descriptor(
  name='AuthedMessage',
  full_name='messaging.AuthedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth', full_name='messaging.AuthedMessage.auth', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='messaging.AuthedMessage.message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=147,
)


_THREADREPLY = _descriptor.Descriptor(
  name='ThreadReply',
  full_name='messaging.ThreadReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth', full_name='messaging.ThreadReply.auth', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thread', full_name='messaging.ThreadReply.thread', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='messaging.ThreadReply.message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=266,
)

_AUTHEDMESSAGE.fields_by_name['auth'].message_type = user__pb2._IDENT
_AUTHEDMESSAGE.fields_by_name['message'].message_type = message__pb2._MESSAGE
_THREADREPLY.fields_by_name['auth'].message_type = user__pb2._IDENT
_THREADREPLY.fields_by_name['thread'].message_type = message__pb2._THREAD
_THREADREPLY.fields_by_name['message'].message_type = message__pb2._MESSAGE
DESCRIPTOR.message_types_by_name['AuthedMessage'] = _AUTHEDMESSAGE
DESCRIPTOR.message_types_by_name['ThreadReply'] = _THREADREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthedMessage = _reflection.GeneratedProtocolMessageType('AuthedMessage', (_message.Message,), dict(
  DESCRIPTOR = _AUTHEDMESSAGE,
  __module__ = 'message_service_pb2'
  # @@protoc_insertion_point(class_scope:messaging.AuthedMessage)
  ))
_sym_db.RegisterMessage(AuthedMessage)

ThreadReply = _reflection.GeneratedProtocolMessageType('ThreadReply', (_message.Message,), dict(
  DESCRIPTOR = _THREADREPLY,
  __module__ = 'message_service_pb2'
  # @@protoc_insertion_point(class_scope:messaging.ThreadReply)
  ))
_sym_db.RegisterMessage(ThreadReply)



_MESSAGESERVICE = _descriptor.ServiceDescriptor(
  name='MessageService',
  full_name='messaging.MessageService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=269,
  serialized_end=451,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='messaging.MessageService.Send',
    index=0,
    containing_service=None,
    input_type=_AUTHEDMESSAGE,
    output_type=message__pb2._THREAD,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Reply',
    full_name='messaging.MessageService.Reply',
    index=1,
    containing_service=None,
    input_type=_THREADREPLY,
    output_type=message__pb2._THREAD,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='messaging.MessageService.Delete',
    index=2,
    containing_service=None,
    input_type=_AUTHEDMESSAGE,
    output_type=message__pb2._THREAD,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGESERVICE)

DESCRIPTOR.services_by_name['MessageService'] = _MESSAGESERVICE

# @@protoc_insertion_point(module_scope)
