# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_pb2 as user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='messaging',
  syntax='proto3',
  serialized_pb=_b('\n\rmessage.proto\x12\tmessaging\x1a\nuser.proto\"k\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\t\x12 \n\x04\x66rom\x18\x02 \x01(\x0b\x32\x12.messaging.Profile\x12\x1e\n\x02to\x18\x03 \x01(\x0b\x32\x12.messaging.Profile\x12\x0c\n\x04\x62ody\x18\x05 \x01(\tJ\x04\x08\x04\x10\x05\"I\n\x06Thread\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12$\n\x08messages\x18\x02 \x03(\x0b\x32\x12.messaging.Messageb\x06proto3')
  ,
  dependencies=[user__pb2.DESCRIPTOR,])




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='messaging.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='messaging.Message.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from', full_name='messaging.Message.from', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='messaging.Message.to', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='messaging.Message.body', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=147,
)


_THREAD = _descriptor.Descriptor(
  name='Thread',
  full_name='messaging.Thread',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='messaging.Thread.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='messaging.Thread.title', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messages', full_name='messaging.Thread.messages', index=2,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=222,
)

_MESSAGE.fields_by_name['from'].message_type = user__pb2._PROFILE
_MESSAGE.fields_by_name['to'].message_type = user__pb2._PROFILE
_THREAD.fields_by_name['messages'].message_type = _MESSAGE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Thread'] = _THREAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:messaging.Message)
  ))
_sym_db.RegisterMessage(Message)

Thread = _reflection.GeneratedProtocolMessageType('Thread', (_message.Message,), dict(
  DESCRIPTOR = _THREAD,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:messaging.Thread)
  ))
_sym_db.RegisterMessage(Thread)


# @@protoc_insertion_point(module_scope)
