# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_pb2 as user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='user_service.proto',
  package='messaging',
  syntax='proto3',
  serialized_pb=_b('\n\x12user_service.proto\x12\tmessaging\x1a\nuser.proto\"T\n\rAuthedProfile\x12\x1e\n\x04\x61uth\x18\x01 \x01(\x0b\x32\x10.messaging.Ident\x12#\n\x07profile\x18\x02 \x01(\x0b\x32\x12.messaging.Profile2\x81\x01\n\x0bUserService\x12\x34\n\nCreateUser\x12\x10.messaging.Ident\x1a\x12.messaging.Profile\"\x00\x12<\n\nSetProfile\x12\x18.messaging.AuthedProfile\x1a\x12.messaging.Profile\"\x00\x62\x06proto3')
  ,
  dependencies=[user__pb2.DESCRIPTOR,])




_AUTHEDPROFILE = _descriptor.Descriptor(
  name='AuthedProfile',
  full_name='messaging.AuthedProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth', full_name='messaging.AuthedProfile.auth', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile', full_name='messaging.AuthedProfile.profile', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=129,
)

_AUTHEDPROFILE.fields_by_name['auth'].message_type = user__pb2._IDENT
_AUTHEDPROFILE.fields_by_name['profile'].message_type = user__pb2._PROFILE
DESCRIPTOR.message_types_by_name['AuthedProfile'] = _AUTHEDPROFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthedProfile = _reflection.GeneratedProtocolMessageType('AuthedProfile', (_message.Message,), dict(
  DESCRIPTOR = _AUTHEDPROFILE,
  __module__ = 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:messaging.AuthedProfile)
  ))
_sym_db.RegisterMessage(AuthedProfile)



_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='messaging.UserService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=132,
  serialized_end=261,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateUser',
    full_name='messaging.UserService.CreateUser',
    index=0,
    containing_service=None,
    input_type=user__pb2._IDENT,
    output_type=user__pb2._PROFILE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetProfile',
    full_name='messaging.UserService.SetProfile',
    index=1,
    containing_service=None,
    input_type=_AUTHEDPROFILE,
    output_type=user__pb2._PROFILE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
