# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import user_pb2 as user__pb2
import user_service_pb2 as user__service__pb2


class UserServiceStub(object):
  """UserService is our user microservice.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateUser = channel.unary_unary(
        '/messaging.UserService/CreateUser',
        request_serializer=user__pb2.Ident.SerializeToString,
        response_deserializer=user__pb2.Profile.FromString,
        )
    self.SetProfile = channel.unary_unary(
        '/messaging.UserService/SetProfile',
        request_serializer=user__service__pb2.AuthedProfile.SerializeToString,
        response_deserializer=user__pb2.Profile.FromString,
        )


class UserServiceServicer(object):
  """UserService is our user microservice.
  """

  def CreateUser(self, request, context):
    """CreateUser creates a user.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetProfile(self, request, context):
    """SetProfile updates a user's profile.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=user__pb2.Ident.FromString,
          response_serializer=user__pb2.Profile.SerializeToString,
      ),
      'SetProfile': grpc.unary_unary_rpc_method_handler(
          servicer.SetProfile,
          request_deserializer=user__service__pb2.AuthedProfile.FromString,
          response_serializer=user__pb2.Profile.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'messaging.UserService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
